dev/bridges/DevActivationBridge.ts, dev/bridges/DevAppBridges.ts, dev/server.ts, package.json, src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/bridges/AppBridges.ts, src/server/bridges/IAppActivationBridge.ts, src/server/bridges/IAppDetailChangesBridge.ts, src/server/bridges/index.ts, src/server/managers/AppSettingsManager.ts
These changes are to support this system running on a multi-instance. Where an App is enabled on one implementation and then another implementation it enables the app on that server because it was enabled on the other.
=> Support multi instance

src/server/compiler/AppCompiler.ts, src/server/misc/Utilities.ts
When importing a file `a.ts` in a file `b.ts` from inside a folder `folder` was resolving to `a.ts` instead of `folder/a.ts` what was causing the compiler to not found the file since from compiler scope the base path is the root and not the path of the current file.
=> [FIX] Imports from inside folders were not resolving correctly

src/server/managers/AppSlashCommandManager.ts, tests/server/managers/AppSlashCommandManager.spec.ts
The usernames property of the rooms on the slash command contexts was not updated to the new style of code, classes, which allows getting the usernames of the users in the rooms.
=> [FIX] Slash Command Contexts Not Supporting Usernames on Rooms

src/definition/accessors/IAppAccessors.ts, src/server/accessors/AppAccessors.ts, tests/server/accessors/AppAccessors.spec.ts
Due to the realisation that access to IModify and IPersistence in the app's lifecycle methods, such as `initialize`, could lead to unintentional repeated runs on Rocket.Chat servers running more than one instance, we're removing those properties from AppAccessors
=> Remove modifier and persistence accessors from AppAccessors

src/definition/messages/IMessageAction.ts, src/definition/messages/MessageProcessingType.ts, src/definition/messages/index.ts
Adds the field introduced in [this PR](https://github.com/RocketChat/Rocket.Chat/pull/12626) to the engine.
No further changes are needed on Rocket.Chat for it to work.
=> Add msg_processing_type field to message action

src/definition/app-schema.json
Uncomplicates the version regex in the `app-schema.json` file. There might be other places where the version regex is applied, but I wanted to get this one in there since it was my reference for the marketplace.
=> Modifies the version regex to reflect marketplace's requirements

src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/managers/AppLicenseManager.ts
This PR improves how the engine triggers inter-instance communication.
Pre-requisite for [this Rocket.Chat PR](https://github.com/RocketChat/Rocket.Chat/pull/15080)
=> Improve logic for better inter-instance communication

src/definition/accessors/IConfigurationExtend.ts, src/definition/accessors/IExternalComponentsExtend.ts, src/definition/accessors/index.ts, src/server/accessors/ConfigurationExtend.ts, src/server/accessors/ExternalComponentExtend.ts, src/server/accessors/index.ts, src/server/managers/AppAccessorManager.ts, src/server/managers/AppExternalComponentManager.ts, tests/server/accessors/ConfigurationExtend.spec.ts, tests/test-data/bridges/appBridges.ts, tests/test-data/bridges/externalComponentBridge.ts
* remove tests externalComponentBridge
=> Resolve reviews for #145

src/server/ProxiedApp.ts
The removed `console.log` was "polluting" the server logs heavily
=> [IMPROVE] Remove console.log

package-lock.json, package.json, src/definition/accessors/IMessageBuilder.ts, src/definition/messages/IMessage.ts, src/definition/slashcommands/SlashCommandContext.ts, src/server/accessors/MessageBuilder.ts, src/server/managers/AppSlashCommandManager.ts, tests/server/accessors/MessageBuilder.spec.ts
Apps will need to update their slash commands for them to send messages correctly aware of the thread.
Implementation provided by https://github.com/RocketChat/Rocket.Chat/pull/15574
=> Add thread support to slash commands

src/definition/accessors/ILivechatRead.ts, src/definition/livechat/ILivechatRoomClosedHandler.ts, src/definition/livechat/IVisitor.ts, src/definition/livechat/index.ts, src/definition/metadata/AppMethod.ts, src/server/accessors/LivechatRead.ts, src/server/bridges/ILivechatBridge.ts, src/server/compiler/AppImplements.ts, src/server/managers/AppListenerManager.ts, tests/test-data/bridges/livechatBridge.ts
Closes https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/188
Ref: https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/188#issue-525827629
It also depends on changes in the Rocket.Chat side: https://github.com/RocketChat/Rocket.Chat/pull/15837
=> Add ILivechatRoomClosedHandler

src/definition/accessors/ILivechatRead.ts, src/server/accessors/LivechatRead.ts, src/server/bridges/ILivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
Deprecate inconsistent livechat methods and add new ones for data fetching
Some methods exposed an API requiring the App developer to know how to build a mongo query to fetch visitors and departments.
Those were deprecated and new methods to fetch such data have been added
=> Update Livechat methods

src/server/AppManager.ts, src/server/bridges/IUserBridge.ts
Ensure Apps have users during update routine
Apps installed on Rocket.Chat before the engine started giving them a user upon installation should be given a user after update, without which the App wouldn't be able to use the latest functionality
=> Ensure App has a user during update routine

src/definition/users/IUser.ts, tests/server/accessors/ModifyCreator.spec.ts
We messed up the IUser definition while finishing app user feature. This PR tries to revert all changes on it and only add an optional `appId` property on it.
Avoid breaking changes and we already achieved the goal with `Partical<IUser>`.
N/A
N/A
=> [FIX] Revert breaking changes on IUser definition

src/definition/accessors/ILivechatRead.ts, src/server/accessors/LivechatRead.ts, src/server/bridges/ILivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
See issue #211 for the detail
Closes #211 
https://github.com/RocketChat/Rocket.Chat/pull/16425
n/a
=> [IMPROVE] Allow to check livechat online status per department

src/server/accessors/LivechatRead.ts, src/server/bridges/ILivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
Introduce the new method `isOnlineAsync` method on the `LivechatRead` accessor and deprecate `isOnline`
The `isOnline` method was lacking an asynchronous signature, which was causing execution problems. In order to avoid a breaking change on the API, we've decided to introduce a new method and deprecate the current one.
=> Introduce the `isOnlineAsync` method and deprecate `isOnline` on `LivechatRead`

src/definition/App.ts, src/definition/IApp.ts, src/server/AppManager.ts, src/server/ProxiedApp.ts
Added a new API **getAppUserUsername** so that apps developver can call `this.getAppUserUsername()` to get the username of the app user directly.
Avoid duplication
https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/2713ef13f5cdb5b7d2c4ef52a9333f698b17239b#commitcomment-37053956
*Priority*: <kbd>moderate</kbd>
=> Add new API getAppUserUsername

src/definition/accessors/IRoomBuilder.ts, src/definition/rooms/IRoom.ts, src/server/accessors/RoomBuilder.ts, src/server/rooms/Room.ts
Add field `uids` to rooms
New implementation of group DMs will be adding this fields to all direct message rooms.
=> Add field `uids` to rooms

src/definition/accessors/IModifyUpdater.ts, src/definition/accessors/IUserUpdater.ts, src/definition/users/IUser.ts, src/server/accessors/ModifyUpdater.ts, src/server/accessors/UserUpdater.ts, src/server/bridges/IUserBridge.ts, tests/test-data/bridges/userBridge.ts
Introduces methods that allow apps to update some user properties
Expanding the framework's API
Rocket.Chat side implementation https://github.com/RocketChat/Rocket.Chat/pull/17077
=> [NEW] User update

README.md
Added one missing instruction for installation of apps-engine as a locally compiled package and some troubleshooting instructions
To help the devs in easy setup
=> Added troubleshooting in README

src/definition/AppStatus.ts, src/definition/metadata/AppInterface.ts, src/definition/metadata/IAppInfo.ts, src/definition/metadata/index.ts, src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/bridges/IListenerBridge.ts, src/server/compiler/AppImplements.ts, src/server/compiler/index.ts, src/server/managers/AppListenerManager.ts, tests/server/compiler/AppFabricationFulfillment.spec.ts, tests/server/compiler/AppImplements.spec.ts, tests/server/managers/AppListenerManager.spec.ts
This is a mechanism that allows an app to register itself as "essential" to an event in the Rocket.Chat lifecycle.
If an app that is "essential" is disabled during the execution of such event, an error is thrown.
Currently, we have a problem regarding the state management of apps in HA setups. Each instance in the cluster has to manage the apps that are enabled/disabled, and should communicate any changes to the other instances when they happen, but this has shown to be unreliable in times when there is high usage.
This mechanism presents a way of "shielding" workspaces that require custom rules for critical events (message sending, room creating, etc.) to take place from this unpredictable problems.
https://github.com/RocketChat/Rocket.Chat/pull/17656
=> New "essentials" mechanism

src/definition/AppStatus.ts, src/definition/errors/AppsEngineError.ts, src/definition/errors/index.ts, src/definition/exceptions/AppsEngineException.ts, src/definition/exceptions/EssentialAppDisabledException.ts, src/definition/exceptions/UserNotAllowedException.ts, src/definition/exceptions/index.ts, src/definition/metadata/AppInterface.ts, src/definition/metadata/AppMethod.ts, src/definition/metadata/IAppInfo.ts, src/definition/metadata/index.ts, src/definition/rooms/IPostRoomUserJoined.ts, src/definition/rooms/IPreRoomUserJoined.ts, src/definition/rooms/IRoomUserJoinedContext.ts, src/definition/rooms/index.ts, src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/bridges/IListenerBridge.ts, src/server/compiler/AppImplements.ts, src/server/compiler/index.ts, src/server/managers/AppListenerManager.ts, src/server/rooms/Room.ts, tests/server/compiler/AppFabricationFulfillment.spec.ts, tests/server/compiler/AppImplements.spec.ts, tests/server/managers/AppListenerManager.spec.ts
* Adds the new `IPreRoomUserJoined` event
* Adds the new `IPostRoomUserJoined` event
* Introduces the `AppsEngineError` class that signals prevention from apps events
The new event will allow apps to provide some access control to rooms.
https://github.com/RocketChat/Rocket.Chat/pull/17487
=> New room event

src/definition/uikit/IUIKitIncomingInteraction.ts, src/definition/uikit/UIKitIncomingInteractionTypes.ts, src/server/managers/AppListenerManager.ts
Adds the `blockId` property to UIKit block interactions interface
This information is already being sent by clients and was just ignored by the engine. It also enriches the context information passed to the Apps
=> Add blockId to uikit block incoming interaction

src/definition/uikit/blocks/Elements.ts
Adds the `multiline` property to `IPlainTextInputElement`
This allows apps to open `textareas` with UIKit library
=> Add multiline property to PlainTextInputElement

src/definition/accessors/ILivechatUpdater.ts, src/definition/livechat/ILivechatTransferEventContext.ts, src/definition/livechat/IPostLivechatRoomTransferred.ts, src/definition/livechat/index.ts, src/definition/metadata/AppInterface.ts, src/definition/metadata/AppMethod.ts, src/server/managers/AppListenerManager.ts
Introduces the `IPostLivechatRoomTransferred` event
New hook that gets executed when its counterparts `livechat.afterForwardChatToDepartment` and `livechat.afterForwardChatToAgent` are triggered
=> [OMNICHANNEL] Add new event

src/definition/metadata/AppInterface.ts, src/definition/metadata/AppMethod.ts, src/definition/package.json, src/definition/uikit/index.ts, src/definition/uikit/livechat/IUIKitLivechatActionHandler.ts, src/definition/uikit/livechat/IUIKitLivechatIncomingInteraction.ts, src/definition/uikit/livechat/UIKitLivechatIncomingInteractionType.ts, src/definition/uikit/livechat/UIKitLivechatInteractionContext.ts, src/definition/uikit/livechat/index.ts, src/server/managers/AppListenerManager.ts
Enables apps to listen to UIKit events that started in the livechat widget (for visitors)
The current UIKit events required a `user` to be always present in the event context, which is not true for events triggered in the livechat widget - the `visitor` is not considered a fully authenticated user.
The new interfaces should allow apps to listen to those events without introducing breaking changes to the API.
https://github.com/RocketChat/Rocket.Chat/pull/18706
This small app has been used for testing purposes https://github.com/d-gubert/conditional-block-test
=> [UIKit] New event handlers for the livechat widget

package.json, src/definition/metadata/IAppInfo.ts, src/server/AppManager.ts, src/server/compiler/AppCompiler.ts, src/server/compiler/AppFabricationFulfillment.ts, src/server/compiler/AppPackageParser.ts, src/server/compiler/ICompilerError.ts, src/server/compiler/ICompilerFile.ts, src/server/compiler/ICompilerResult.ts, src/server/compiler/IParseAppPackageResult.ts, src/server/compiler/index.ts, src/server/misc/Utilities.ts, tests/server/compiler/AppCompiler.spec.ts, tests/server/compiler/AppFabricationFulfillment.spec.ts, tests/server/misc/DisabledApp.spec.ts
Removing the compilation process for the apps. From this point on, we're expecting the apps package to contain their compiled versions already.
This is just part of the project - most of the work will be done on other packages.
Rocket.Chat PR: https://github.com/RocketChat/Rocket.Chat/pull/18687
By doing this we achieve:
* A smaller dependency tree for the package, since we will not require the `typescript` package anymore.
* A smaller memory footprint in the Rocket.Chat server, as we will not load `typescript` in runtime anymore.
* A smaller surface for compilation errors to happen when updating the Apps-Engine version in a running server.
* A shorter start-up time for the Rocket.Chat server, as it will not need to compile all installed apps anymore.
* A more flexible development …
=> Remove ts compiler

src/definition/livechat/ILivechatEventContext.ts, src/definition/livechat/IPostLivechatGuestSaved.ts, src/definition/livechat/IPostLivechatRoomSaved.ts, src/definition/livechat/index.ts, src/definition/metadata/AppInterface.ts, src/definition/metadata/AppMethod.ts, src/server/managers/AppListenerManager.ts
Added new interfaces to give the apps support to catch events when an omnichannel's guest have their information updated. Same for when the room gets its info updated.
To solve the issue https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/270
=> [NEW][Omnichannel] add new events for onGuest and onRoom info save

package-lock.json, package.json, src/definition/package.json, src/server/accessors/UploadCreator.ts
Remove file type detection in the upload bridge
The Rocket.Chat repo already has access to the libraries used to do so, and by removing this from the Apps-Engine, we keep things here as simple as possible
=> Remove file-type detection on upload

src/definition/accessors/IHttp.ts
Add a new optional property `encoding` to the interface IHttpRequest
Make sure we can using `http.get` to download binary data correctly.
https://open.rocket.chat/group/t9xgtnadgqwf3xkzh?msg=x5EsHiqtzv7rJj3qR (Private)
The PR on the RocketChat side: https://github.com/RocketChat/Rocket.Chat/pull/19002
=> [NEW] Add support for the "encoding" option in HTTP requests

package.json
Refer to title 😬 
This is being more of a hassle than helpful as ALL doc files are updated and are not pushed at the same time with the code. We need to review the workflow around this.
=> Remove doc generation from pre-push hook

src/definition/accessors/INotifier.ts, src/server/accessors/Notifier.ts, src/server/bridges/IMessageBridge.ts, tests/test-data/bridges/messageBridge.ts
Added a new type indicator API:
```ts
typing(options: ITypingOptions): Promise<() => Promise<void>>;
```
Closes #330 
Closes #303
RFC: https://forums.rocket.chat/t/rfc-30-apps-engine-add-support-for-user-typing-indicator/8684 (private)
=> User Typing indicator API

src/definition/accessors/IConfigurationModify.ts, src/definition/package.json, src/server/accessors/ConfigurationModify.ts, src/server/managers/AppAccessorManager.ts, tests/server/accessors/ConfigurationModify.spec.ts
Adds the `ISchedulerModify` interface as a member of `IConfigurationModify`
This allows apps to control scheduled jobs from events that don't have access to the `IModify`
=> Add the scheduler modifier to the configurationModify object

src/server/AppManager.ts
Don't store changes in the apps' statuses during server startup
During startup, all apps state are set to `initializing` as part of the load process. At the end of the process, the apps' status are set to the value that was before `initilizing`, which is stored at `ProxiedApp`'s `previousStatus` property.
But when in a HA environment, all servers write this information to the same document, making `previousStatus` from the `ProxiedApp` and the actual status stored in the database both as `initializing` because multiple writes were done, thus not setting the correct state as `enabled` or `disabled`. This causes the some apps' states to appear as `disabled` in the apps' list. Not storing those changes in the state of the app during startup fixes this issue.
=> [FIX] Apps were being disabled during RC server startup

src/server/accessors/MessageExtender.ts, src/server/accessors/RoomExtender.ts, tests/server/accessors/MessageExtender.spec.ts, tests/server/accessors/RoomExtender.spec.ts
- Added exceptions in the `addCustomField` methods in the `MessageExtender` and `RoomExtender` classes when the key to be added contains a period.
The added exceptions were described in the `addCustomField` method's documentation (description) from both classes, but were not really implemented in their code.
=> [FIX] Add exception to the addition of keys that contain periods

src/definition/IApp.ts
- Add missing deprecation notice to the `getAppUserUsername` method in the `IApp` interface.
The deprecation notice must be added since the `getAppUserUsername` method is planned to be removed in the next major version.
[Task - ClickUp](https://app.clickup.com/t/98bbwe)
=> [FIX] Add deprecation notices to all instances of the getAppUserUsername method

src/definition/accessors/IUserRead.ts, src/server/accessors/UserRead.ts, src/server/bridges/IUserBridge.ts, tests/server/accessors/UserRead.spec.ts, tests/test-data/bridges/userBridge.ts
- Updated all instances of the `getAppUser` method so as to make the `appId` parameter optional.
This PR implements the changes described in this [task](https://app.clickup.com/t/98bbwg), and moves closer to completely removing the `getAppUser` method's parameter in the near future.
[Task - ClickUp](https://app.clickup.com/t/98bbwg)
=> [IMPROVEMENT] Make the parameter on the getAppUser method optional

src/server/permissions/checkers/AppPersistenceBridge.ts
Fix wrong method names in persistence bridge
=> Fix persistence bridge

src/server/compiler/modules/net.ts, src/server/permissions/AppPermissions.ts, src/server/permissions/checkers/AppApisBridge.ts, src/server/permissions/checkers/AppCommandsBridge.ts, src/server/permissions/checkers/AppHttpBridge.ts, src/server/permissions/checkers/AppLivechatBridge.ts, src/server/permissions/checkers/AppMessageBridge.ts, src/server/permissions/checkers/AppPersistenceBridge.ts, src/server/permissions/checkers/AppSchedulerBridge.ts
After a review with some other team members, these are the suggestions that came up:
Having the `.general` suffix for the permissions was not a good name. The suggestion was to change it to `.manage`, but in the end, removing the suffixes altogether seemed like a better option. This way, we can have developers declare the permissions in the manifest file as `{ name: "scheduler" }`, for instance, and we maintain our internal structure by defining a "default" scope for those permissions.
We could also observe the permissions could be split into two categories: _internal_ and _system_ permissions. _Internal_ permissions were the ones that shared the `.general` suffix - they represent a feature that the app uses to manage it's own functionality internally and how it interfaces with the …
=> Permissions review

src/definition/uploads/IFileUploadContext.ts, src/server/permissions/checkers/AppSchedulerBridge.ts
See title
Providing a stream so apps can access the file content would break the functionality, as once the stream has finished emitting data, it's not possible to rewind it. This would mean that whenever an app reads the contents of the stream, any subsequent app, and even Rocket.Chat, would not be able to do so.
Changing it to a Buffer allows all parties to read the contents of the file.
=> Rergession: Change file content from stream to Buffer

src/definition/uikit/UIKitInteractionPayloadFormatter.ts
See title
Rocket.Chat is introducing the support to the `showIcon` property in the view payload sent to show/update in order to support the concept of "core apps" (more info on this later), which won't have icons available to show. However, this property is not intended to be used directly by third-party apps, so it has been added as a constant value.
=> Add showIcon to view payload in modal interactions from UIKit

src/server/AppManager.ts
Cancel all jobs registered by the app as soon as it gets loaded (server startup) when the app status is marked as "disabled"
During the startup process, all apps have their "configurationExtend" method run, regardless of whether they are enabled. In this method, we also define the processors (job functions) that will be run by the app, including the ones that should be run as soon as they get registered, without manual triggering. This tasks that run automatically were run because of the app being loaded, not taking in consideration the app's state.
=> [Fix] Jobs running when the app is disabled

src/definition/accessors/IMessageBuilder.ts, src/server/accessors/MessageBuilder.ts, tests/server/accessors/MessageBuilder.spec.ts
- Added the **`setUpdateData` method** in the `MessageBuilder`. This method is similar to the `setData` method, but it does not delete the message's ID (hence, it is possible to use the `ModifyUpdater` object to update the message later using the `messageBuilder`).
The `setUpdateData` method is introduced in order to allow messages' updates within the `messageBuilder` object. It has been built as a solution to the issue #343.
[Issue #343](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/343)
The editor (user who updated the message) is also a mandatory parameter from the `setUpdateData` method, since this attribute is necessary in updates.
=> [FIX] Missing a method to allow messages' updates within the MessageBuilder (#343)

src/server/accessors/LivechatRead.ts, src/server/bridges/ILivechatBridge.ts, src/server/permissions/checkers/AppLivechatBridge.ts
Some permission checkers for the Livechat bridge are missing, causing runtime errors
=> Fix missing permission checkers

src/definition/accessors/ICloudWorkspaceRead.ts, src/server/managers/AppPermissionManager.ts, src/server/permissions/checkers/AppCloudBridge.ts
Improve comments on the CloudWorkspace related classes/interfaces.
=> Improve comments on CloudWorkspace

src/definition/exceptions/UserNotAllowedException.ts, src/definition/metadata/AppInterface.ts, src/definition/metadata/AppMethod.ts, src/definition/rooms/IPostRoomUserLeave.ts, src/definition/rooms/IPreRoomUserLeave.ts, src/definition/rooms/IRoomUserLeaveContext.ts, src/definition/rooms/index.ts, src/server/managers/AppListenerManager.ts
Added: New event interfaces for pre/post user leaving a room, `IPreRoomUserLeave` and `IPostRoomUserLeave`
[Task](https://app.clickup.com/t/98bc63)
=> IPreRoomUserLeave and IPostRoomUserLeave event interfaces

src/definition/rooms/IRoom.ts
**Added** the `description` value to a `IRoom` interface. The `description` value refers to a room topic.
To allow developers to get the `description` information from a room.
Fixes https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/203
=> Chore: Add description value to IRoom interface

src/definition/scheduler/IProcessor.ts, src/definition/scheduler/IRecurringSchedule.ts
Adds a property lets the developer decide whether they want the first iteration of a recurring task to be executed immediately instead of waiting for the defined interval to complete
=> Add `skipImmediate` property to the IRecurringSchedule interface

src/definition/App.ts, src/definition/accessors/IAppInstallationContext.ts, src/definition/accessors/index.ts, src/definition/metadata/AppMethod.ts, src/server/AppManager.ts
**Added:** `onInstall` event method.
[ClickUp Task](https://app.clickup.com/t/98bbxj)
Fixes  https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/397
Complements https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/407
=> [NEW] App `onInstall` event

src/client/AppsEngineUIClient.ts, src/client/AppsEngineUIHost.ts, src/definition/package.json
Fixes a bug that causes the listener to error out when it receives an event with no data
=> [FIX] Apps-Engine UI comms incorrectly validated data in listener

src/server/accessors/ServerSettingRead.ts, src/server/accessors/SettingRead.ts
- Updated ISettingRead getValueById
- Updated IServerSettingRead getValueById
```
public async getValueById(id: string): Promise<any> {
const set = await this.settingBridge.getOneById(id, this.appId);
if (typeof set === 'undefined') {
throw new Error(`No Server Setting found, or it is unaccessible, by the id of "${id}".`);
}
return set.value || set.packageValue;
}
```
The issue is with the BOOLEAN settings. When `packageValue` (default value) is set to true and `value` (current value) if false,
It returns true because of `OR ||`.
Similar issue when setting value is `''` for STRING Setting.
Properly returns BOOLEAN and STRING setting
=> [FIX] Update getValueById for properly getting value for BOOLEAN and STRING Setting

package-lock.json, src/server/AppManager.ts
Splits the process of removing an app from the Apps-Engine in two parts: remove it from the DB and then remove the instantiated class from the set of apps in the manager
This allows us to make different calls in Rocket.Chat, calling the whole removal process when the user clicks the "Uninstall" button, but only removing the app instance from the local server memory when it receives a notification that an app has been uninstalled in the cluster
* Rocket.Chat implementation https://github.com/RocketChat/Rocket.Chat/pull/22415
=> [IMPROVE] Split app removal process

src/server/bridges/LivechatBridge.ts
Fix wrong permission validation for livechat bridge
It's a fix. It's self explanatory
=> Fix livechat bridge

src/server/bridges/LivechatBridge.ts
Fix wrong permission check in the `doFindDepartmentByIdOrName` method
=> Fix wrong permission on department read method

src/definition/accessors/ISchedulerExtend.ts, src/definition/accessors/ISchedulerModify.ts, src/server/accessors/SchedulerExtend.ts, src/server/accessors/SchedulerModify.ts, src/server/bridges/SchedulerBridge.ts, src/server/managers/AppSchedulerManager.ts
In the methods that create tasks (scheduleRecurring and scheduleOnce) return the id of the document created in the database so the user can cancel each task individually.
=> [IMPROVE] Return task ids when using the scheduler api

src/definition/App.ts
Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>
Changed deprecation notice text for `app.getAppUsername()`
The correct alternative is `read.getUserReader().getAppUser()` not `read.getAppUser()`
https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/ccc46d087723fa19dafc97a61c202f832316c0ed/src/definition/accessors/IRead.ts#L30
https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/ccc46d087723fa19dafc97a61c202f832316c0ed/src/definition/accessors/IUserRead.ts#L7-L16
=> [FIX] alternate method name in app.getAppUsername() deprecation notice

src/definition/accessors/IRoomBuilder.ts
Correct incorrect method name of `addMemberByUsername` to `addMemberToBeAddedByUsername` in the JSDoc for addUsername
There is no method called `addMemberByUsername` which wrongly [shown here](https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/accessors_iroombuilder.iroombuilder.html#addusername)
=> [FIX] Typo `addMemberToBeAddedByUsername` instead of `addMemberByUsername`

docs/interfaces/settings_isetting.isetting.html, src/definition/settings/ISetting.ts, src/definition/settings/SettingType.ts
Added new interfaces for multi-select settings within app
=> [NEW] Add Multi-Select setting interfaces on Apps

src/server/ProxiedApp.ts
Currently, when an app throws any of the known exceptions that extend `AppsEngineException` to prevent a process from finishing (e.g. `FileUploadNotAllowedException`), the execution re-throws the error object before storing any of the apps logs to the database.
This PR changes this behavior, so that logs are saved regardless of the type of error caught during execution
Losing the logs limits the debugging capabilities of Apps
=> [IMPROVE] Move call to store logs to appropriate place

src/definition/accessors/ILivechatUpdater.ts, src/server/accessors/LivechatUpdater.ts, src/server/bridges/LivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
* Add an optional param named `closer` into `LivechatUpdater.closeRoom` so that we can close the room with the correct closer.
closes #373
When closing the room with the Apps, the room closer and the close room message sender will always be set to the visitor. This is not a correct behavior because the visitor does not perform that function.
This is not a very clean approach, we actually should pass something like `closeData` which contains all the needed data for Rocket.Chat close room function, but to avoid breaking change we can accept this approach right now
Rocket.Chat issue: RocketChat/Rocket.Chat#21025
=> [NEW] Add possibility to set room closer to LivechatUpdater.closeRoom

src/definition/email/IEmailDescriptor.ts, src/definition/email/IPreEmailSent.ts, src/definition/email/IPreEmailSentContext.ts, src/definition/email/index.ts, src/definition/metadata/AppInterface.ts, src/definition/metadata/AppMethod.ts, src/server/managers/AppListenerManager.ts
Adds definitions and listener for new event `IPreEmailSent`, that allows for manipulation of email messages sent and interruption of transmission if needed
=> [NEW] Add new event for pre email

src/definition/accessors/IUserRead.ts, src/server/accessors/UserRead.ts, src/server/bridges/UserBridge.ts, tests/test-data/bridges/userBridge.ts
We understand it's not so interesting allow users to see how many unread messages other users have as a 'core' feature, but if the admin wants to install an app that does that, well then it's free to do so.
=> [NEW] UserRead getBadgeCount Method

src/definition/accessors/IUIController.ts, src/definition/uikit/IUIKitInteractionType.ts, src/definition/uikit/UIKitIncomingInteractionContainer.ts, src/definition/uikit/UIKitIncomingInteractionTypes.ts, src/definition/uikit/UIKitInteractionPayloadFormatter.ts, src/definition/uikit/UIKitInteractionResponder.ts, src/server/accessors/UIController.ts
=> [NEW] Open uikit contextual bar

gulpfile.js, src/definition/accessors/IConfigurationExtend.ts, src/definition/accessors/IUIExtend.ts, src/definition/accessors/index.ts, src/definition/metadata/AppMethod.ts, src/definition/package.json, src/definition/ui/IUIActionButtonDescriptor.ts, src/definition/ui/UIActionButtonContext.ts, src/definition/ui/index.ts, src/definition/uikit/IUIKitActionHandler.ts, src/definition/uikit/IUIKitIncomingInteraction.ts, src/definition/uikit/UIKitIncomingInteractionTypes.ts, src/definition/uikit/UIKitInteractionContext.ts, src/server/AppManager.ts, src/server/accessors/ConfigurationExtend.ts, src/server/accessors/UIExtend.ts, src/server/bridges/AppActivationBridge.ts, src/server/managers/AppAccessorManager.ts, src/server/managers/AppListenerManager.ts, src/server/managers/AppSlashCommand.ts, src/server/managers/UIActionButtonManager.ts, src/server/permissions/AppPermissions.ts, tests/server/accessors/AppAccessors.spec.ts, tests/server/accessors/ConfigurationExtend.spec.ts, tests/server/managers/AppAccessorManager.spec.ts, tests/server/managers/AppApiManager.spec.ts, tests/server/managers/AppSettingsManager.spec.ts, tests/server/managers/AppSlashCommandManager.spec.ts, tests/test-data/bridges/activationBridge.ts
Allows apps to register action buttons in Rocket.Chat UI
Because IT'S AWESOME
=> [NEW] Action buttons registry

src/server/AppManager.ts, src/server/managers/UIActionButtonManager.ts
Action buttons, once registered in the button manager, were never removed, even if the app was disabled or uninstalled.
Of course, as the manager itself is kept in memory, restarting the Apps-Engine would have them removed if the app was uninstalled.
=> [FIX] Action buttons were not removed from manager

src/server/AppManager.ts
During the procedure to enable an app, the engine wasn't persisting the correct app status to the databasing, causing subsequent calls to `AppManager.load` method (usually called during Rocket.Chat server startup) to leave apps in a "disabled" state
=> [FIX] Apps not being enabled in framework load time

src/definition/accessors/IUserUpdater.ts, src/server/accessors/UserUpdater.ts
This PR adds a bridge method to change the status and status text.
This functionality will help the apps to set custom status better.
=> [NEW] Adding bridge to change both status and status text

src/server/AppManager.ts
Current update flow caused slash commands registered by apps to retain a reference to the outdated version of the app, essentially failing to update slash command code.
=> [FIX] App update flow caused slashcommands to run old code

src/server/compiler/modules/index.ts
In some use cases, apps' dependencies require the module to work properly. For instance the [`oauth`](https://www.npmjs.com/package/oauth) package uses it internally to handle URLs.
https://nodejs.org/docs/latest-v12.x/api/querystring.html
=> [NEW] Allow 'querystring' native module inside apps

src/definition/users/IUser.ts, src/definition/users/IUserSettings.ts, src/server/accessors/UserBuilder.ts
Exposed a new property on the User object that allows apps to read the user's preferred language
So that apps can provide a more personalized experience :rocket: 
Connected core PR: https://github.com/RocketChat/Rocket.Chat/pull/25514
=> [NEW] Get user's preferred language via apps

src/server/oauth2/OAuth2Client.ts
During the OAuth process, the `redirect_uri` wasn't being formatted properly, making the login process fail.
=> [FIX] Faulty redirect_uri path concatenation

src/definition/uikit/blocks/Objects.ts
Added URL to the options object to allow the Overflow component to open it.
This feature will allow opening a link inside the overflow component, as it's possible with the button component. We will need it to develop the Google Drive app.
[Task](https://app.clickup.com/t/2mkhme4)
=> [NEW] Add url prop in the OptionObject

src/definition/package.json, src/server/AppManager.ts, src/server/managers/AppSchedulerManager.ts
This PR changes the logic behind when an app is disabled to keep the schedulers saved
Currently, whenever an app is disabled, all the jobs it scheduled are deleted from the database. However, this causes confusion if the app is re-enabled, as users will expect jobs scheduled previously to run anyways.
=> Keeping schedulers after disabling an app

src/definition/uikit/blocks/Elements.ts
Added a new property to `input elements` so actions can be triggered based on user activity.
https://user-images.githubusercontent.com/733282/174858175-5ea53046-c791-493e-859b-b80431e94ffa.mp4
[Test app used in the video](https://github.com/RocketChat/apps-pocs-and-tests/tree/main/input-element-block-action)
This is needed for the development of the Google Drive app.
Related PRs:
- https://github.com/RocketChat/fuselage/pull/747
- https://github.com/RocketChat/Rocket.Chat/pull/25949
=> [NEW] allow dispatchment of actions from input elements

src/server/AppManager.ts
- Make the _update app_ action work in the same way as _disable app_ when it comes to keeping scheduled jobs in the db and not deleting them.
Way to reproduce:
- use the test app [agenda4test](https://github.com/RocketChat/apps-pocs-and-tests/tree/main/agendav4test) to schedule a job by running the slash command `/scheduler r` (this will create a job that runs every 10 seconds and posts a message to the _general channel_)
- disable app and then enable it again (still works);
- update the app via cli or zip file (this is where the patched code does its job; the task will keep running as it should);
- uninstall the app (no leftover data in the database)
=> [FIX] Keep scheduled jobs when updating an app

src/definition/package.json, src/server/accessors/ModifyCreator.ts, src/server/accessors/ModifyUpdater.ts, src/server/accessors/UIController.ts, src/server/misc/UIHelper.ts
Assign blockId, appId, and actionId for the blocks and elements when calling openSurfaceView/updateSurfaceView method and on finish message builder.
[Task AE-55](https://rocketchat.atlassian.net/jira/software/c/projects/AE/boards/28?modal=detail&selectedIssue=AE-55)
=> [FEAT] Assign ids to blocks and elements

src/server/oauth2/OAuth2Client.ts
- Added support for OAuth2 Clients that require parameters in Body as x-www-form-urlencoded Content-Type.
- Backwards compatible, does not affect client that don't require parameters in Body.
We need this in using Microsoft Graph API and other OAuth2 Clients.
=> [New] Support for x-www-form-urlencoded Body Params in OAuth2 calls

src/server/AppManager.ts, src/server/storage/IAppStorageItem.ts, src/server/storage/index.ts
Adapting the startup flow by making it simply loading apps and instantiating them into memory, not enabling them in the same routine
This allows us for a more granular control on the host side to validate installed apps without having to enable them in the process
AE-73
AE-74
This PR is required for https://github.com/RocketChat/Rocket.Chat/pull/27848
=> [IMPROVE] Adapt startup flow

docs/enums/settings_settingtype.settingtype.html, src/definition/settings/SettingType.ts
Adds "Password" to the list of allowed setting types
So apps can create password settings.
=> [NEW] Add "password" setting type

src/server/AppManager.ts
Check the app's status not to enable it if it was manually disabled.
Every app was enabled at the server's startup, even the ones the user disabled. With the fix, the ones that were disabled manually by the user keep their statuses.
Related to [PR](https://github.com/RocketChat/Rocket.Chat/pull/28322)
[AE-109](https://rocketchat.atlassian.net/browse/AE-109)
[AE-109]: https://rocketchat.atlassian.net/browse/AE-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Regression: Enable app individual loading routine

src/definition/accessors/IModifyDeleter.ts, src/definition/users/IBotUser.ts, src/server/accessors/ModifyCreator.ts, src/server/accessors/ModifyDeleter.ts, src/server/bridges/UserBridge.ts
The first proposal assumed that the bot doesn't consume billable seats. But, that isn't true, it consumes.
Before, the app created and deleted just bot users and now we changes some parameters to allow the app to create and delete bot and app users.
AECO-62
=> fix: Create and delete bot user

src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/compiler/AppCompiler.ts, src/server/managers/AppApi.ts, src/server/managers/AppSlashCommandManager.ts
- Makes event broadcast to happen _after_ the app has been removed, not before
- Fixes a race condition between multiple calls to `manager.remove` or `manager.removeLocal` that causes apps to not be able to be uninstalled
- Validates `this.appTouchedCommands` has data before accessing it
- Add awaits to support LogStorage to be async now
=> [FIX] Fix event broadcast to happen after the app has been removed

src/server/AppManager.ts
Added a new method `addLocal` which is the correspondent version of `add`  that will load an app from the database and start it up.
Previously the `loadOne` method was used to load apps when an instance of Rocket.Chat received a notification that an app had been installed somewhere else in the cluster. However, due to changes to this method, it was actually breaking this flow. The new method is added to provide the lost functionality
Rocket.Chat PR with implementation: https://github.com/RocketChat/Rocket.Chat/pull/29180
=> [FIX] loadOne doesn't fetch app data from database

src/definition/settings/ISetting.ts, src/definition/settings/SettingType.ts
- Added the room pick setting type
Many apps require adding a room name in settings for specific use purposes; currently, the developer could allow admins to enter room names as a string; however, after this feature release, adding rooms will be pretty convenient as a simple click-n-select.
Setting preview:
The room setting value after selecting the rooms will be:
```jsx
value: [ { _id: 'GENERAL' }, { _id: 'cFhgqGnZAY5dq85Z4' } ]
```
The `roomPick` setting is already implemented in the core. I have also tried to improve the comments for the value, haha, since many times, I had to console log to view the `value` structure after a change in settings. Thank you!
=> Add Room Pick Setting

src/definition/uikit/UIKitIncomingInteractionTypes.ts, src/definition/uikit/UIKitInteractionContext.ts, src/server/managers/AppListenerManager.ts
Some recent UIKit changes broke API compatibility, this PR fixes the situation.
Breaking changes in the public API should only happen on major bumps.
=> regression: UIKit changes broke compatibility

src/server/marketplace/IMarketplaceInfo.ts
Adding the `isEnterpriseOnly` flag in the marketplace info
This flag will be used in the Rocket.chat to determine whether is possible to enable an app or not
=> feat: adding isEnterpriseOnly flag

src/definition/accessors/IUIController.ts, src/definition/ui/IToastMessagePaylaod.ts, src/definition/uikit/IUIKitInteractionType.ts, src/definition/uikit/UIKitInteractionPayloadFormatter.ts, src/server/accessors/UIController.ts
This reverts commit cd85e757933f9bf84411bf9cc66ea47eab099117.
Reverting #657 
We should consider a different approach that avoid use toast messages as an exclusive ui-interaction.
=> chore: Revert "feat: Add toast message interaction (#657)"

deno-runtime/deno.jsonc, deno-runtime/deno.lock, deno-runtime/lib/messenger.ts, deno-runtime/main.ts, package-lock.json, package.json, src/server/runtime/AppsEngineDenoRuntime.ts
Start using the `jsonrpc-lite` package to format communication between the processes
I was essentially implementing this package previously in the Deno process, but since both Node and Deno would need to share this and the package covered more cases than my implementation, I decided to go with it for now.
=> Adopt jsonrpc-lite package

deno-runtime/AppObjectRegistry.ts, deno-runtime/lib/accessors/_test.ts, deno-runtime/lib/accessors/mod.ts, deno-runtime/main.ts
The new `AppObjectRegistry` will hold references to instances of objects created by the app to pass to the `ConfigurationExtend` or `ConfigurationModify` accessors
=> Create the AppObjectRegistry

deno-runtime/lib/accessors/_test.ts, deno-runtime/lib/accessors/mod.ts, src/definition/api/IApiEndpoint.ts, src/server/managers/AppApi.ts, src/server/runtime/AppsEngineDenoRuntime.ts, tests/test-data/utilities.ts
Config accessors are used by apps to register several components which are not serializable because they include functions that need to be called in the future.
Here we adapt the calls to store instances when needed
=> Adapted config accessors

deno-runtime/handlers/app/construct.ts, deno-runtime/handlers/app/handler.ts, deno-runtime/lib/messenger.ts, deno-runtime/main.ts, src/server/runtime/AppsEngineDenoRuntime.ts
Refactor Deno handling for app
=> Refactor app construct handler

deno-runtime/lib/accessors/mod.ts, deno-runtime/lib/accessors/modify/ModifyCreator.ts, deno-runtime/lib/accessors/modify/ModifyUpdater.ts, src/definition/App.ts, src/server/runtime/AppsEngineDenoRuntime.ts
The proxies used to send method calls as request over IPC ended up also sending calls to the `toJSON` method as a request. This, of course, makes no sense and only causes problems.
This PR also adds a `toJSON` implementation to the `App` abstract class, as the app instance can be sent over for configuration methods if the object sent has a reference to the App instance. E.g. instantiating a slashcommand class that takes the instace of the App as parameter via constructor.
=> Prevent proxies from sending toJSON calls via IPC

deno-runtime/handlers/app/handler.ts, deno-runtime/handlers/listener/handler.ts, deno-runtime/handlers/slashcommand-handler.ts, deno-runtime/handlers/tests/listener-handler.test.ts, deno-runtime/handlers/tests/slashcommand-handler.test.ts, deno-runtime/lib/messenger.ts, deno-runtime/lib/roomFactory.ts, src/definition/exceptions/AppsEngineException.ts, src/server/ProxiedApp.ts, src/server/managers/AppListenerManager.ts
Add the handlers for listener methods in Deno and refactor the AppListenerManager usage
=> Refactor listener methods

src/definition/App.ts, src/definition/IApp.ts, src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/managers/AppApiManager.ts, src/server/managers/AppSchedulerManager.ts, src/server/managers/AppSlashCommandManager.ts, tests/server/accessors/AppAccessors.spec.ts, tests/server/managers/AppApiManager.spec.ts, tests/server/managers/AppSlashCommandManager.spec.ts, tests/server/misc/DisabledApp.spec.ts
`getStatus` now needs to be async because we need to ask the Deno subprocess about the app's status
=> Refactor `IApp.getStatus` implementation and usages

src/server/ProxiedApp.ts, src/server/managers/AppListenerManager.ts, src/server/managers/AppSlashCommand.ts, src/server/managers/AppVideoConfProvider.ts, tests/server/accessors/AppAccessors.spec.ts, tests/server/managers/AppApiManager.spec.ts, tests/server/managers/AppSlashCommand.spec.ts, tests/server/managers/AppSlashCommandManager.spec.ts, tests/server/managers/AppVideoConfProvider.spec.ts
=> Remove method `hasMethod` from ProxiedApp and its usages

deno-runtime/handlers/app/construct.ts, deno-runtime/main.ts, src/server/runtime/AppsEngineDenoRuntime.ts
The request for `app:construct` can be split into two due to the size of the payload, so now requests sent from Node will have a `MESSAGE_SEPARATOR` sequence and Deno will buffer any chunk that doesn't have one
Also introduced an `await` in the `parseOutput` function to avoid unhandled promise rejections
=> Fix app construct handler

deno-runtime/main.ts, src/server/AppManager.ts, src/server/runtime/AppsEngineDenoRuntime.ts
Both ends of the socket now can receive multiple messages or incomplete messages and will handle this appropriately
=> Improve incoming message handling on both Node and Deno

deno-runtime/handlers/api-handler.ts, deno-runtime/handlers/app/construct.ts, deno-runtime/handlers/app/handleGetStatus.ts, deno-runtime/handlers/app/handleOnDisable.ts, deno-runtime/handlers/app/handleOnInstall.ts, deno-runtime/handlers/app/handleOnPreSettingUpdate.ts, deno-runtime/handlers/app/handleOnSettingUpdated.ts, deno-runtime/handlers/app/handleOnUninstall.ts, deno-runtime/handlers/app/handleSetStatus.ts, deno-runtime/handlers/scheduler-handler.ts, deno-runtime/handlers/videoconference-handler.ts
Fix imports of Apps-Engine files inside `deno-runtime` to be of `type` only (otherwise it breaks execution)
Fix `require('node:buffer')` inside the `wrapAppCode` function, which should be `require('buffer')` since we are customizing the `require` function there
Run linter on some files
=> Fix batch (2)

deno-runtime/main.ts
Change deno's main loop to work on incoming messages asynchronously.
If the deno process tries to request something from the main process and wait for its results, it would put itself into a soft lock, as the response event is triggered by the main loop as well. 
If the queue is process asynchronously, then the deno process can continue to process new messages even while an old one is waiting for something.
=> fix: soft lock when an app uses its accessors

src/server/AppManager.ts
Add undo step to installation process to stop the subprocess in case there are errors during installation.
Without this, further attempts to install the same app will result in error because the runtime manager will reject saying the app already has a runtime associated with it
=> Add undo step to recover from installation errors

src/server/managers/AppSettingsManager.ts, tests/server/managers/AppSettingsManager.spec.ts
Remove unnecessary accessor parameters from settings event handler calls as they were breaking the flow
=> Remove accessors being sent as parameters on settings event handlers

src/server/runtime/AppsEngineDenoRuntime.ts
Now the `getStatus` method in `DenoSubprocessController` will return `AppStatus.UNKNOWN` if the Deno process has been terminated
=> Prevent timeout if subprocess not available for getStatus

deno-runtime/handlers/app/handler.ts, deno-runtime/lib/messenger.ts, src/server/runtime/AppsEngineDenoRuntime.ts
Add debug log information to app method handlers
Also, add a 4-character id to each message, outside of the JSONRPC object
This is necessary for the Node process to be able to handle multiple messages sent quickly
=> Add logs to app method handlers on Deno

src/definition/accessors/ILivechatRead.ts, src/server/accessors/LivechatRead.ts, src/server/bridges/LivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
- Added `findRoomsByAgentId` to LivechatBridge
- Added 'getLivechatRoomsByAgentId` to ILivechatRead
We need to have that information available to share it accordingly to a Customer Request.
- https://rocketchat.atlassian.net/browse/PROSVC-55
=> feat: PROSVC-55 findRoomsByAgentId

deno-runtime/handlers/app/construct.ts
Preventing the app from accessing the underlying console object and accidentally pushing content to stdout
=> Overwrite the name `console` when evaluating the app's code in Deno

deno-runtime/lib/accessors/mod.ts, deno-runtime/lib/codec.ts
- Fix `providedApiEndpoints` - Deno was saving the api endpoints in an object, but the original property was an array
- Prevent App instances from being serialized by msgpack - To use certain features, such as slash commands or api enpoints, apps usually create a subclass of those that include a reference to the main app class; but serializing the app class can be difficult as several properties are not serializable. So now we prevent that from happening
=> Fix codec and providedApiEndpoints

deno-runtime/handlers/scheduler-handler.ts, deno-runtime/handlers/tests/scheduler-handler.test.ts
Fix scheduler execution. The job was not being executed since the application searched for the wrong process ID.
=> fix: scheduler execution

deno-runtime/deno.lock, deno-runtime/lib/messenger.ts
`Deno.stdout.write` is not guaranteed to write the entire buffer. It returns the number of bytes written, which may be less than the length of the buffer.
I've replaced it with `writeAll` from the standard library, which writes the entire buffer or throws an error if it fails.
=> Fix Deno not writing full messages to stdout

deno-runtime/handlers/api-handler.ts, deno-runtime/handlers/app/handler.ts, deno-runtime/handlers/slashcommand-handler.ts
- Prevent app:getStatus from generating logs - it was becoming difficult to see relevant logs
- Wrong variable was being logged in the API handler - it was logging a function's toString instead of the method from the request
- Add logs to slash command handler
=> Improve logs

src/server/runtime/AppsEngineDenoRuntime.ts
When we receive a message from Deno, we do not need to await the handler function. It ends up blocking the handling of any subsequent message, causing false timeouts.
We've already removed the await on the Deno side, the behavior should be the same on Node
=> Remove unnecessary await in Node's message handler

deno-runtime/lib/accessors/mod.ts, src/server/accessors/UploadCreator.ts
Remove buffer converters between apps.engine and app since the msgpack is already doing it.
[VM2-13](https://rocketchat.atlassian.net/browse/VM2-13)
[VM2-13]: https://rocketchat.atlassian.net/browse/VM2-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove buffer converter

deno-runtime/lib/accessors/mod.ts, src/server/runtime/AppsEngineDenoRuntime.ts
The modifications worked when we had the source code symlinked to Rocket.Chat. However, when it was installed via npm/yarn, the Deno subprocess would not start, because it lacked the permission to read the parent `node_modules` directory which contains packages used by the Apps-Engine.
=> Fix permissions for Deno subprocess when package is installed

src/definition/accessors/ILivechatRead.ts, src/server/accessors/LivechatRead.ts, src/server/bridges/LivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
- add `open` prefix to find/count by AgentId methods
- make clear the scope of the methods
=> add Open prefix to find/count by agent methods

src/definition/oauth2/IOAuth2.ts, src/server/oauth2/OAuth2Client.ts
Fix the import of URL interface
It is affecting apps that uses the OAuth2 bridge
[CORE-187](https://rocketchat.atlassian.net/browse/CORE-187)
[CORE-187]: https://rocketchat.atlassian.net/browse/CORE-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix the url import usage on oauth2

package-lock.json, package.json, src/server/AppManager.ts, src/server/ProxiedApp.ts, src/server/managers/AppListenerManager.ts, src/server/managers/AppRuntimeManager.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts, src/server/runtime/deno/bundler.ts, src/server/runtime/deno/codec.ts, tests/server/compiler/AppFabricationFulfillment.spec.ts, tests/server/managers/AppApiManager.spec.ts, tests/server/managers/AppSlashCommandManager.spec.ts, tests/server/runtime/DenoRuntimeSubprocessController.spec.ts, tests/test-data/utilities.ts
- Move the AppsEngineDenoRuntime to its own folder
- Call bundler before sending construct command to subprocess
Legacy apps were not bundled during packaging, but this structure makes dealing with the package much harder on the Deno subprocess.
So now we bundle apps that need it before sending the package to the subprocess.
We couldn't use the bundler from the @rocket.chat/apps-compiler package due to the different expectations it deals with, so we just adapted the code to this specific case
=> Bundle legacy apps

deno-runtime/handlers/api-handler.ts, deno-runtime/handlers/tests/api-handler.test.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts, tests/server/runtime/DenoRuntimeSubprocessController.spec.ts
The fix should solve problems where Rocket.chat throws an exception when executing the endpoint, but the application doesn't catch it. We return an ' Internal server error ' to avoid letting the client of the request go without a response.
=> fix: handle api endpoint execution exceptions

deno-runtime/main.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts
Add a 'ping' method to the IPC protocol, called every 5s
This allows us to check the health of the subprocess
=> Add ping method

src/definition/accessors/IRoomRead.ts, src/server/accessors/RoomRead.ts, src/server/bridges/RoomBridge.ts, tests/server/accessors/RoomRead.spec.ts, tests/test-data/bridges/roomBridge.ts
- Updated the Room bridge's `getMessages` method to return the messages in a batch
- Previously, the `getMessages` method was available, but when using and making the call, there was an error `Method not implemented`, which caused confusion as well as provided no other way to fetch room messages
- [ADR](https://adr.rocket.chat/0063)
- [Rocket.Chat Bridge PR](https://github.com/RocketChat/Rocket.Chat/pull/32176)
=> feat: Implement the Apps Engine Room message read bridge

deno-runtime/lib/messenger.ts, deno-runtime/main.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts
Make the ping/pong mechanism use simple strings instead of a full JSON RPC message.
This saves some CPU cycles by avoiding the creation of an object and also its encoding by msgpack. Pings now always take less than 1ms for the whole roundtrip
=> Improve ping time

src/server/runtime/deno/AppsEngineDenoRuntime.ts
Title explains it.
With vm2 there was no error when an app tried to access an environment variable, it simply returned `undefined` for all of them. But Deno throws an error when that happens, and this breaks compatibility with some apps. That's why we're trying to prevent it.
=> Allow Deno process to read NODE_EXTRA_CA_CERTS env var

src/server/managers/AppListenerManager.ts
There was an issue with some apps that didn't implement executeViewCloseHandler. This causes opened modals to be open forever on UI. This is because when the UI attempts to close it, it calls the aforementioned handler, and since it didn't exist, apps engine errored out.
This returned an empty response to the UI, which ignored the response and continued to show the view.
[rocketchat.atlassian.net/browse/CORE-401](https://rocketchat.atlassian.net/browse/CORE-401)
=> fix: Add default behavior to `executeViewCloseHandler` for all apps that don't implement it

src/definition/accessors/IRoomRead.ts, src/definition/messages/IMessageRaw.ts, src/definition/messages/index.ts, src/definition/users/IUserLookup.ts, src/server/accessors/RoomRead.ts, src/server/bridges/RoomBridge.ts, tests/server/accessors/RoomRead.spec.ts, tests/test-data/bridges/roomBridge.ts, tests/test-data/utilities.ts
-  Added a new interface, `IMessageRaw` for the `getMessages` method 
- Correct the tests for `getMessages` with the new type
- Add a common `createAttachments` method
- Since the `IMessage` required making additional DB trips
- The `createAttachments` method avoids duplicating the same attachment code chunk across two methods.
- [JIRA](https://rocketchat.atlassian.net/browse/SAFE-28)
- [Core-side dependent PR](https://github.com/RocketChat/Rocket.Chat/pull/32176)
=> feat: Introduce new msg interface and correct the tests

deno-runtime/handlers/listener/handler.ts, deno-runtime/handlers/tests/listener-handler.test.ts
Fix incorrect translation of room data on listeners of message events
=> regression: incorrect translation of room data on listeners of message events

src/definition/accessors/ILivechatCreator.ts, src/server/accessors/LivechatCreator.ts, src/server/bridges/LivechatBridge.ts, tests/test-data/bridges/livechatBridge.ts
This pull request is related to the changes introduced in [Rocket.Chat PR #32620](https://github.com/RocketChat/Rocket.Chat/pull/32620) and [Apps.WhatsApp PR #72](https://github.com/RocketChat/Apps.WhatsApp/pull/72).
The modifications in this PR update the `createVisitor` and `doCreateVisitor` functions to align with the new expected behavior. These functions will now return the complete records of the created entities, rather than just their IDs.
- [Jira OPI-5 - Remove redundant getLivechatVisitors from defineVisitor function](https://rocketchat.atlassian.net/browse/OPI-5)
- [Rocket.Chat PR #32620](https://github.com/RocketChat/Rocket.Chat/pull/32620)
- [Apps.WhatsApp PR #72](https://github.com/RocketChat/Apps.WhatsApp/pull/72)
=> feat: ILivechatCreator `createAndReturnVisitor`  method

src/definition/messages/IMessage.ts, src/definition/uikit/IUIKitSurface.ts, src/server/accessors/MessageBuilder.ts, src/server/misc/UIHelper.ts
=> fix: use `LayoutBlock` instead of `Block`

deno-runtime/lib/accessors/builders/MessageBuilder.ts, src/definition/accessors/IMessageBuilder.ts, src/definition/messages/IMessage.ts, src/definition/uikit/IUIKitSurface.ts, src/server/accessors/MessageBuilder.ts, src/server/messages/Message.ts, src/server/misc/UIHelper.ts
=> chore: LayoutBlock

src/server/ProxiedApp.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts
Add an option to the runtime request functions to allow for ad-hoc overriting of the default timeout configuration (10s)
Long time outs on "Pre" listener events were causing actions on the RocketChat side to take too long if a subprocess became faulty
The API ended up being a bit off due to the current architecture constrains of the `ProxiedApp`. We'll need to reevaluate at a later date.
=> feat(deno-runtime): limit timeout of "Pre" listener events to 1s

src/server/AppManager.ts, src/server/managers/AppRuntimeManager.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts, src/server/runtime/deno/LivenessManager.ts, src/server/runtime/deno/ProcessMessenger.ts, tests/server/runtime/DenoRuntimeSubprocessController.spec.ts
Extracted two new components from the `DenoRuntimeSubprocessController` class:
- ProcessMessenger - controls transport of messages to the subprocess
- LivenessManager - controls the ping processes and restarts
Refactor the ping functionality to add the following:
- Keep track of consecutive ping timeouts. If reaches limit (currently 4), tries to restart the subprocess
- Keep track of restarts. If reaches limit (currently 3), stops restarting and leaves app in "broken" state
- Pings will now be aborted if the process exits (either due to a Deno error or a kill)
- Pings will now only start after the process is ready.
If the Deno subprocess goes to an invalid state and stop responding, we try to restart it in hopes that this recovers the process nicely.
=> feat(deno-runtime): restart app process if it times out consecutively

src/definition/rooms/IRoomUserLeaveContext.ts
[CORE-498](https://rocketchat.atlassian.net/browse/CORE-498)
[CORE-498]: https://rocketchat.atlassian.net/browse/CORE-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: include removedBy to IUserLeaveContext

deno-runtime/handlers/tests/videoconference-handler.test.ts, deno-runtime/handlers/videoconference-handler.ts, src/server/managers/AppVideoConfProvider.ts
Similarly to how the `checkPre` methods work on the listener manager, we have optional methods in video conf providers that should not block execution if they are not implemented
=> fix: optional methods in video conf providers not being handled correctly

deno-runtime/lib/accessors/mod.ts, deno-runtime/lib/accessors/modify/ModifyCreator.ts, deno-runtime/lib/accessors/modify/ModifyUpdater.ts, src/server/runtime/deno/AppsEngineDenoRuntime.ts
Catch errors that happen during the execution of subprocess' requests in `DenoRuntimeSubprocessController` and send a proper JSON RPC error response to the subprocess.
These errors were not being sent over and the subprocess just waited indefinitely for a response.
Apps should be able to handle exceptions that happen when something goes wrong with their calls
=> fix: handler errors no being sent to subprocess

src/server/AppManager.ts
Two types of errors were preventing updates and uninstall in some cases:
1. When apps fail to start and have an empty runtime assigned
2. If the process is already dead
In these cases, we can actually ignore the errors, as our intention was really to make sure the deno subprocess was killed
=> fix: errors during updates and uninstallations when runtime or subprocess is invalid

.gitignore, package.json, scripts/postinstall.js, src/server/runtime/deno/AppsEngineDenoRuntime.ts, tsconfig-lint.json
Change installation to force the deno cache directory to be created inside the apps-engine own directory.
This simplifies installation in manual deployments
=> feat: improve package installation and deno caching

src/definition/livechat/ILivechatRoom.ts
it seems those fields are very common on apps, but they have no direct access
=> feat: add closed by  and closer on livechat `ILivechatRoom`

src/server/managers/AppListenerManager.ts
When running a livechat uikit interaction, the AppListenerManager wraps the interactionData in an instance of `UIKitLivechatBlockInteractionContext`, but when the deno runtime receives a request for livechat interactions, it also wraps the params in an instance of the same class. This was causing apps to receive this interaction data in the wrong format.
I haven't tested it on an actual app.
=> fix: livechat interaction handler is receiving its context data wrapped in a second instance of the context class
