- package.json
- tests/server/misc/DisabledApp.spec.ts
- tests/server/misc/Utilities.spec.ts
Create tests for server/misc/Utilities and server/misc/DisabledApp
> Create misc tests

- package-lock.json
- src/server/bridges/IAppCommandBridge.ts
- src/server/errors/CommandHasAlreadyBeenTouchedError.ts
- src/server/errors/index.ts
- src/server/managers/AppSettingsManager.ts
- src/server/managers/AppSlashCommandManager.ts
- src/server/managers/AppSlashCommandRegistration.ts
- tests/server/errors/CommandHasAlreadyBeenTouchedError.spec.ts
- tests/server/managers/AppAccessorManager.spec.ts
- tests/server/managers/AppSettingsManager.spec.ts
- tests/server/managers/AppSlashCommandManager.spec.ts
- tests/server/managers/AppSlashCommandRegistration.spec.ts
- tests/test-data/bridges/appBridges.ts
- tests/test-data/bridges/appDetailChanges.ts
- tests/test-data/bridges/commandBridge.ts
- tests/test-data/logStorage.ts
Continues work on the manager tests. Also, due to testing several aspects of the command handling have been improved logically and for performance.
> Manager Tests

- src/definition/messages/IPostMessageUpdated.ts
- src/definition/messages/IPreMessageUpdatedExtend.ts
- src/definition/messages/IPreMessageUpdatedModify.ts
- src/definition/messages/IPreMessageUpdatedPrevent.ts
- src/definition/messages/index.ts
- src/definition/metadata/AppMethod.ts
- src/server/compiler/AppImplements.ts
- src/server/managers/AppListenerManger.ts
I just followed the steps of the `message sent` handlers and implemented the ones for `message updates`.
This app in the `edit-tests` branch can be used to test the additions: https://github.com/cardoso/Rocket.Chat.ContentFilter/tree/edit-tests
Closes #63 
PR needs to be merged in main repo: https://github.com/RocketChat/Rocket.Chat/pull/11993
> [NEW] Add handlers for message updates

- src/definition/accessors/IModify.ts
- src/definition/messages/IMessage.ts
- src/server/accessors/MessageBuilder.ts
- tests/server/accessors/MessageBuilder.spec.ts
Requires merge in main repo: https://github.com/RocketChat/Rocket.Chat/pull/11939
Closes #40
> [NEW] Add setGroupable to Message Builder

- gulpfile.js
- src/definition/messages/IMessageAction.ts
- src/definition/messages/IMessageAttachment.ts
- src/definition/messages/MessageActionButtonsAlignment.ts
- src/definition/messages/MessageActionType.ts
- src/definition/messages/index.ts
As the message actions require the type property and currently there is only one type of action item.
> [NEW] Action button types

- src/definition/api/ApiEndpoint.ts
- src/definition/api/IApi.ts
- src/definition/api/IApiEndpoint.ts
> [FIX] Wrong documentation related to the API usage

- src/definition/accessors/IPersistence.ts
- src/server/accessors/Persistence.ts
- src/server/bridges/IPersistenceBridge.ts
- tests/server/accessors/Persistence.spec.ts
- tests/test-data/bridges/persisBridge.ts
Implements updateByAssociation into persistence.
> [IMPROVE] Persistence updateByAssociation

- src/definition/accessors/IRoomRead.ts
- src/server/accessors/ModifyCreator.ts
- src/server/accessors/RoomRead.ts
- src/server/bridges/IRoomBridge.ts
- tests/server/accessors/ModifyCreator.spec.ts
- tests/server/accessors/RoomRead.spec.ts
- tests/test-data/bridges/roomBridge.ts
Implements getMembers;
Implements getDirectByUsernames;
> [IMPROVE] Room methods 

- src/definition/accessors/IPersistence.ts
- src/server/accessors/Persistence.ts
- src/server/bridges/IPersistenceBridge.ts
- tests/server/accessors/Persistence.spec.ts
- tests/test-data/bridges/persisBridge.ts
Depends on https://github.com/RocketChat/Rocket.Chat/pull/13239
> Add method updateByAssociations to Persistence

- src/definition/accessors/IModify.ts
- src/definition/messages/IMessage.ts
- src/server/accessors/MessageBuilder.ts
- src/server/messages/Message.ts
- tests/server/accessors/MessageBuilder.spec.ts
Depends on https://github.com/RocketChat/Rocket.Chat/pull/13248
> Add parseUrls field to message

- src/client/AppEmbeddedSDK.ts
- src/client/constants/index.ts
- src/client/utils/index.ts
- src/definition/externalComponent/IWebHooks.ts
- src/definition/package.json
Hi @d-gubert. I implemented AppEmbeddedSDK, can you please review it?
> Apps.engine.ui.sdk

- .circleci/config.yml
@d-gubert need to define if the publish process should increase the version and set the build number.
> Deploy versions to NPM via CI

- src/definition/livechat/IDepartment.ts
- src/definition/livechat/ILivechatRoom.ts
- src/definition/livechat/index.ts
Depends on https://github.com/RocketChat/Rocket.Chat/pull/15407
> Access livechat room’s deparment data

- src/server/AppManager.ts
- src/server/managers/AppExternalComponentManager.ts
- src/server/managers/AppSlashCommandManager.ts
> [Alpha] Add missing unregister component method

- src/definition/externalComponent/IExternalComponent.ts
> Add new location to the external components called MODAL

- src/definition/accessors/IExternalComponentsExtend.ts
resolved review: https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/145#discussion_r330056313
> Add documentation to register method

- README.md
Some instructions on how to get a dev environment up and running
> Update README with development instructions

- src/server/AppManager.ts
**Before:**
<kbd>![before](https://user-images.githubusercontent.com/32427260/67143797-bca38400-f2a1-11e9-9679-f80bb1b6a20b.png)</kbd>
**After:**
<kbd>![after](https://user-images.githubusercontent.com/32427260/67143799-c3ca9200-f2a1-11e9-9946-e7321851cbba.png)</kbd>
> Show detailed logs when meeting compiler errors

- .github/pull_request_template.md
- src/definition/package.json
Add a PR template
We still don't have any and this one is quite simple and helpful 😄 
Shoutout to @guicruzzs for the inspiration!
> Add PR template

- README.md
List all features
Better visualization of each feature
> List all features

- src/definition/uikit/UIKitInteractionResponder.ts
Fix modal property
The previous value was wrong
> Fix modal update

- src/definition/uikit/IUIKitIncomingInteraction.ts
- src/definition/uikit/UIKitIncomingInteractionContainer.ts
- src/definition/uikit/UIKitIncomingInteractionTypes.ts
- src/definition/uikit/blocks/Elements.ts
- src/server/managers/AppListenerManager.ts
A container represents the source of an UI Kit interaction.
Some actions need to know from where it was triggered.
> Add container definition

- src/definition/uikit/IUIKitIncomingInteraction.ts
- src/definition/uikit/UIKitIncomingInteractionContainer.ts
- src/definition/uikit/blocks/BlockBuilder.ts
- src/definition/uikit/blocks/Elements.ts
Updates to the API while it's in `beta`
Improving the DX
> Uikit updates

- src/definition/uikit/UIKitIncomingInteractionContainer.ts
Improve uikit incoming interaction container type
To improve DX
> Add UIKit Incoming Interaction Container Type

- src/definition/uikit/blocks/BlockBuilder.ts
- src/definition/uikit/blocks/Blocks.ts
- src/definition/uikit/blocks/Elements.ts
- src/definition/uikit/blocks/Objects.ts
> Add overflow menu element

- src/definition/package.json
- src/definition/uikit/UIKitIncomingInteractionContainer.ts
Fixes `IUIKitIncomingInteractionContainerType`s
> Fix UIKit container types

- README.md
- package-lock.json
- package.json
- src/definition/App.ts
- src/definition/accessors/IDiscussionBuilder.ts
- src/definition/accessors/IModifyCreator.ts
- src/definition/accessors/IRoomBuilder.ts
- src/definition/accessors/IUserRead.ts
- src/definition/accessors/index.ts
- src/definition/metadata/RocketChatAssociations.ts
- src/definition/package.json
- src/definition/rooms/IRoom.ts
- src/server/accessors/DiscussionBuilder.ts
- src/server/accessors/ModifyCreator.ts
- src/server/accessors/RoomBuilder.ts
- src/server/accessors/UserRead.ts
- src/server/bridges/IRoomBridge.ts
- tests/server/accessors/UserRead.spec.ts
- tests/test-data/bridges/roomBridge.ts
Beta version.
Current new features:
* Discussion builder
* New method for apps to grab the user assigned for them
> Beta 1.14.0

- package.json
- src/definition/metadata/IAppInfo.ts
- src/server/AppManager.ts
- src/server/compiler/AppCompiler.ts
- src/server/compiler/AppFabricationFulfillment.ts
- src/server/compiler/AppPackageParser.ts
- src/server/compiler/ICompilerError.ts
- src/server/compiler/ICompilerFile.ts
- src/server/compiler/ICompilerResult.ts
- src/server/compiler/IParseZipResult.ts
- src/server/compiler/index.ts
- src/server/misc/Utilities.ts
- tests/server/compiler/AppCompiler.spec.ts
- tests/server/compiler/AppFabricationFulfillment.spec.ts
- tests/server/misc/DisabledApp.spec.ts
Reverts RocketChat/Rocket.Chat.Apps-engine#307
These changes will be released in the next version (v1.19)
> Revert "Remove ts compiler"

- src/definition/accessors/ILivechatUpdater.ts
- src/definition/livechat/IVisitor.ts
- src/definition/rooms/IRoom.ts
- src/server/accessors/LivechatUpdater.ts
- src/server/bridges/ILivechatBridge.ts
- tests/test-data/bridges/livechatBridge.ts
Provide a new Livechat Api by `modify.getUpdater().getLivechatUpdater().setCustomFields`
https://app.clickup.com/t/24zmb4
PR in the RC side: https://github.com/RocketChat/Rocket.Chat/pull/18912
> [NEW] Provide new Livechat Api setCustomFields

- src/definition/uploads/IUploadDescriptor.ts
- src/definition/uploads/IUploadDetails.ts
- src/server/accessors/UploadCreator.ts
Add new optional property visitorToken to IUploadDescriptor
Allow apps to upload files by a LiveChat visitor
> [NEW] Add new optional property visitorToken to IUploadDescriptor

- src/server/misc/Utilities.ts
Module resolution had not been adapted to read JS files from package
> Regression: fix module resolution with no compiler

- src/definition/accessors/ISchedulerExtend.ts
- src/definition/accessors/ISchedulerModify.ts
- src/definition/scheduler/IOnetimeSchedule.ts
- src/definition/scheduler/IProcessor.ts
- src/definition/scheduler/IRecurringSchedule.ts
- src/definition/scheduler/index.ts
- src/server/accessors/SchedulerExtend.ts
- src/server/bridges/IAppSchedulerBridge.ts
- src/server/managers/AppSchedulerManager.ts
- tests/test-data/bridges/schedulerBridge.ts
To be able to run tasks without the need for manually scheduling them
> Allow jobs to be scheduled along with processor registration

- src/definition/rooms/IPostRoomUserJoined.ts
- src/server/managers/AppListenerManager.ts
See title
This allows apps handling the `IPostRoomUserJoined` event to interact with the system in a variety of ways, such as sending a message, scheduling a job, etc.
> Inject modifier into IPostRoomUserJoined event handler

- src/server/AppManager.ts
> Normalize app filenames in update function

- src/definition/permissions/IPermission.ts
- src/server/AppManager.ts
- src/server/managers/AppPermissionManager.ts
- src/server/permissions/checkers/AppCommandsBridge.ts
- src/server/permissions/checkers/index.ts
> Adjustments in the Permission System PR

- src/server/permissions/checkers/index.ts
> Fix UiInteractionBridge.notifyUser permission checker not found

- src/definition/accessors/ICloudWorkspaceRead.ts
- src/definition/accessors/IRead.ts
- src/definition/accessors/index.ts
- src/definition/cloud/IWorkspaceToken.ts
- src/definition/permissions/IPermission.ts
- src/server/accessors/CloudWorkspaceRead.ts
- src/server/accessors/Reader.ts
- src/server/bridges/AppBridges.ts
- src/server/bridges/ICloudWorkspaceBridge.ts
- src/server/bridges/index.ts
- src/server/errors/PermissionDeniedError.ts
- src/server/managers/AppAccessorManager.ts
- src/server/managers/AppPermissionManager.ts
- src/server/permissions/AppPermissions.ts
- src/server/permissions/checkers/AppCloudBridge.ts
- src/server/permissions/checkers/index.ts
- tests/server/accessors/Reader.spec.ts
- tests/test-data/bridges/appBridges.ts
- tests/test-data/bridges/cloudBridge.ts
Adds the new CloudWorkspace functionality. 
It allows apps to request the access token for the workspace it's installed on, so it can perform actions with other Rocket.Chat services, such as the Omni Gateway.
> Cloud workspace bridge

- package-lock.json
- package.json
- src/definition/accessors/ICloudWorkspaceRead.ts
- src/definition/accessors/IMessageBuilder.ts
- src/definition/accessors/IRead.ts
- src/definition/accessors/index.ts
- src/definition/cloud/IWorkspaceToken.ts
- src/definition/permissions/IPermission.ts
- src/server/AppManager.ts
- src/server/accessors/CloudWorkspaceRead.ts
- src/server/accessors/MessageBuilder.ts
- src/server/accessors/Reader.ts
- src/server/bridges/AppBridges.ts
- src/server/bridges/ICloudWorkspaceBridge.ts
- src/server/bridges/index.ts
- src/server/errors/PermissionDeniedError.ts
- src/server/managers/AppAccessorManager.ts
- src/server/managers/AppPermissionManager.ts
- src/server/permissions/AppPermissions.ts
- src/server/permissions/checkers/AppCloudBridge.ts
- src/server/permissions/checkers/index.ts
- tests/server/accessors/MessageBuilder.spec.ts
- tests/server/accessors/Reader.spec.ts
- tests/test-data/bridges/appBridges.ts
- tests/test-data/bridges/cloudBridge.ts
* [FIX] Jobs running when the app is disabled (#378)
* [FIX] Missing a method to allow messages' updates within the MessagBuilder (#364)
* [NEW] Cloud workspace bridge (#382)
> Beta 1.23.0

- src/definition/App.ts
- src/definition/accessors/IAppUninstallationContext.ts
- src/definition/accessors/index.ts
- src/definition/metadata/AppMethod.ts
- src/server/AppManager.ts
**Added:** `onUninstall` event method.
[ClickUp Task](https://app.clickup.com/t/98bbxj)
Fixes  https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/397
Complements https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/404
> [NEW] App `onUninstall` event

- src/definition/accessors/ILivechatRead.ts
- src/definition/livechat/IDepartment.ts
- src/server/accessors/LivechatRead.ts
- src/server/bridges/ILivechatBridge.ts
- src/server/permissions/AppPermissions.ts
- src/server/permissions/checkers/AppLivechatBridge.ts
- tests/test-data/bridges/livechatBridge.ts
Add a new method that allows apps to fetch all departments in the server.
> [NEW] Get departments

- src/definition/accessors/IModify.ts
- src/definition/accessors/IModifyDeleter.ts
- src/definition/accessors/index.ts
- src/server/accessors/Modify.ts
- src/server/accessors/ModifyDeleter.ts
- src/server/bridges/IRoomBridge.ts
- tests/test-data/bridges/roomBridge.ts
**Added:** A new `Modify` interface (`IModifyDeleter`), which contains a `deleteRoom` method.
**Updated:** The rooms bridge, adding a `delete` method.
[Task](https://app.clickup.com/t/4d32pq)
Fixes https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/398
> [NEW] Delete room method

- src/definition/accessors/ILivechatRead.ts
- src/server/accessors/LivechatRead.ts
- src/server/bridges/LivechatBridge.ts
- src/server/permissions/AppPermissions.ts
- tests/test-data/bridges/livechatBridge.ts
Added a new method in Livechat's bridge to retrieve the messages of a room.
> [NEW] Get livechat's room transcript via bridge method

- src/definition/livechat/ILivechatRoom.ts
Add the new fields in Omnichannel rooms to identify the source of the room
Fields have been added to Rocket.Chat types
https://github.com/RocketChat/Rocket.Chat/pull/23090
> [NEW] Omnichannel source type

- src/server/AppManager.ts
> [FIX] App update flow causes errors in HA setups

- package-lock.json
- package.json
- src/definition/package.json
- src/server/AppManager.ts
* Fix app update flow which was causing errors in HA setups
> Release 1.28.1

- src/definition/accessors/IRoomBuilder.ts
- src/definition/livechat/ILivechatRoom.ts
- src/definition/rooms/IRoom.ts
- src/server/accessors/RoomBuilder.ts
> chore: adding set custom icon method

- gulpfile.js
- src/definition/accessors/IConfigurationExtend.ts
- src/definition/accessors/IUIExtend.ts
- src/definition/accessors/index.ts
- src/definition/metadata/AppMethod.ts
- src/definition/package.json
- src/definition/ui/IUIActionButtonDescriptor.ts
- src/definition/ui/UIActionButtonContext.ts
- src/definition/ui/index.ts
- src/definition/uikit/IUIKitActionHandler.ts
- src/definition/uikit/IUIKitIncomingInteraction.ts
- src/definition/uikit/UIKitIncomingInteractionTypes.ts
- src/definition/uikit/UIKitInteractionContext.ts
- src/server/AppManager.ts
- src/server/accessors/ConfigurationExtend.ts
- src/server/accessors/UIExtend.ts
- src/server/bridges/AppActivationBridge.ts
- src/server/managers/AppAccessorManager.ts
- src/server/managers/AppListenerManager.ts
- src/server/managers/AppSlashCommand.ts
- src/server/managers/UIActionButtonManager.ts
- src/server/permissions/AppPermissions.ts
- tests/server/accessors/AppAccessors.spec.ts
- tests/server/accessors/ConfigurationExtend.spec.ts
- tests/server/managers/AppAccessorManager.spec.ts
- tests/server/managers/AppApiManager.spec.ts
- tests/server/managers/AppSettingsManager.spec.ts
- tests/server/managers/AppSlashCommandManager.spec.ts
- tests/test-data/bridges/activationBridge.ts
Allows apps to register action buttons in Rocket.Chat UI
Because IT'S AWESOME
> [NEW] Action buttons registry

- src/server/AppManager.ts
Fix on App update regarding API information
Why not?
> [FIX] Adding the necessary information about the API when update the app

- src/definition/livechat/ILivechatRoom.ts
Add label prop to source in livechat room
This label will be shown in the room info
> [IMPROVE] Add label prop to source in livechat room

- src/server/accessors/UserUpdater.ts
Adding Enum to help the app developers to use the setStatus method
> [CHORE] Adding Enum to identify the status

- src/definition/metadata/AppInterface.ts
- src/definition/metadata/AppMethod.ts
- src/definition/users/IPostUserCreated.ts
- src/definition/users/IPostUserDeleted.ts
- src/definition/users/IPostUserLoggedIn.ts
- src/definition/users/IPostUserLoggedOut.ts
- src/definition/users/IPostUserStatusChanged.ts
- src/definition/users/IPostUserUpdated.ts
- src/definition/users/IUserContext.ts
- src/definition/users/IUserStatusContext.ts
- src/definition/users/IUserUpdateContex.ts
- src/definition/users/index.ts
- src/server/managers/AppListenerManager.ts
[Task](https://app.clickup.com/t/22wqv6k)
> [NEW] Add new events after user login, logout and change his status

- src/definition/messages/IMessage.ts
- src/definition/messages/IMessageFollowContext.ts
- src/definition/messages/IMessagePinContext.ts
- src/definition/messages/IMessageReactionContext.ts
- src/definition/messages/IPostMessageFollowed.ts
- src/definition/messages/IPostMessagePinned.ts
- src/definition/messages/IPostMessageReacted.ts
- src/definition/messages/index.ts
- src/definition/metadata/AppInterface.ts
- src/definition/metadata/AppMethod.ts
- src/definition/users/IUserLookup.ts
- src/definition/users/index.ts
- src/server/managers/AppListenerManager.ts
Added definition and listeners for new events IPostMessageReacted, IPostMessagePinned and IPostMessageFollowed
Added properties in the Message interface to give more context about pinned messages.
[Task](https://app.clickup.com/t/22wqd51)
[Rocket.chat PR](https://github.com/RocketChat/Rocket.Chat/pull/25337)
> [NEW] Add message react, follow and pin message events

- src/definition/ui/UIActionButtonContext.ts
- Added: `UIActionButtonContext.ROOM_SIDEBAR_ACTION`
The Rocket.chat will need this to add the App Room action button
> [NEW] Adding enum option to room sidebar action button

- src/server/bridges/RoomBridge.ts
> [FIX] Wrong permission ID on Permission Denied notification

- src/definition/package.json
- src/definition/videoConfProviders/IVideoConfProvider.ts
- src/definition/videoConferences/IVideoConference.ts
- src/server/bridges/VideoConferenceBridge.ts
- src/server/errors/AVideoConfProviderAlreadyExistsError.ts
- src/server/errors/NoVideoConfProviderRegisteredError.ts
- src/server/errors/VideoConfProviderAlreadyExistsError.ts
- src/server/errors/VideoConfProviderNotRegisteredError.ts
- src/server/errors/index.ts
- src/server/managers/AppVideoConfProviderManager.ts
- tests/server/accessors/VideoConfProviderExtend.spec.ts
- tests/server/managers/AppVideoConfProviderManager.spec.ts
- tests/test-data/bridges/videoConferenceBridge.ts
- tests/test-data/utilities.ts
> [NEW] Enable Multiple Video Conference Providers

- src/definition/videoConferences/IVideoConference.ts
> [NEW] Livechat VideoConference type

- src/definition/App.ts
> Small spelling correction

- .circleci/config.yml
- gulpfile.js
- package.json
> [CHORE] Publish package when merging to new/videoconf

- tests/server/accessors/VideoConferenceBuilder.spec.ts
> [NEW] Extra test for video conference builder

- src/definition/metadata/AppMethod.ts
- src/definition/videoConfProviders/IVideoConfProvider.ts
- src/server/managers/AppVideoConfProvider.ts
- src/server/managers/AppVideoConfProviderManager.ts
- tests/server/accessors/VideoConfProviderExtend.spec.ts
- tests/server/managers/AppVideoConfProviderManager.spec.ts
- tests/test-data/utilities.ts
> [NEW] [Video Conference] Configure Provider Capabilities

- package-lock.json
- package.json
> Chore: Update adm-zip package

- .circleci/config.yml
- gulpfile.js
- package.json
Remove videoconf specific automations
They won't be needed anymore as the branch was already merged
> Chore: Remove videoconf automations

- src/definition/videoConferences/IVideoConference.ts
> Regression: Outdated call status list

- package-lock.json
- src/definition/accessors/IUIController.ts
- src/server/accessors/UIController.ts
Implements a new method to open and other to update the modal or the contextual bar to replace the individual ones.
> [NEW] Method to open modal and contextualbar 

- src/server/runtime/AppsEngineVM2Runtime.ts
- Removed: Module resolution logging
> Chore: Removing module resolution log

- src/server/oauth2/OAuth2Client.ts
Looks like this PR breaks the OAuth flow of the Google APIs
Reverts RocketChat/Rocket.Chat.Apps-engine#554
> Revert "[New] Support for x-www-form-urlencoded Body Params in OAuth2 calls"

- src/definition/AppStatus.ts
- src/server/AppManager.ts
- src/server/ProxiedApp.ts
- src/server/errors/InvalidInstallationError.ts
- src/server/managers/AppSignatureManager.ts
This pull request adds app signature verification during the load process. If the signature is invalid, the app status is set to `INVALID_INSTALLATION`. This ensures that only apps with valid installations are loaded in the system.
[AE-71](https://rocketchat.atlassian.net/browse/AE-71)
[AE-71]: https://rocketchat.atlassian.net/browse/AE-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AE-71]: https://rocketchat.atlassian.net/browse/AE-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEAT] Validate app signature

- package-lock.json
- package.json
- src/definition/AppStatus.ts
- src/server/AppManager.ts
- src/server/ProxiedApp.ts
- src/server/bridges/AppBridges.ts
- src/server/bridges/IInternalFederationBridge.ts
- src/server/bridges/index.ts
- src/server/errors/InvalidInstallationError.ts
- src/server/managers/AppSignatureManager.ts
- src/server/storage/IAppStorageItem.ts
- tests/test-data/bridges/appBridges.ts
- tests/test-data/bridges/internalFederationBridge.ts
Reverts RocketChat/Rocket.Chat.Apps-engine#585
Now we're ready to merge it
> Re-introduce "[FEAT] Add checksum and signature to apps"

- src/server/managers/AppSignatureManager.ts
Remove settings from the checksum validation.
> [FIX] Remove settings from checksum fields

- src/definition/rooms/IPostRoomCreate.ts
- src/server/managers/AppListenerManager.ts
> new: pass IModify reference to IPostRoomCreate event

- package-lock.json
- package.json
> chore: bump vm2 version to 3.9.15

- package-lock.json
- package.json
> chore: bump vm2 version to 3.9.16

- package.json
> 1.38.1-alpha

- package-lock.json
- package.json
> chore: bump vm2 version to 3.9.17

- src/definition/accessors/IModerationModify.ts
- src/definition/accessors/IModifyDeleter.ts
- src/definition/accessors/IUserUpdater.ts
- src/server/accessors/ModerationModify.ts
- src/server/accessors/ModifyDeleter.ts
- src/server/accessors/UserUpdater.ts
- src/server/bridges/MessageBridge.ts
- src/server/bridges/ModerationBridge.ts
- src/server/bridges/UserBridge.ts
- tests/test-data/bridges/messageBridge.ts
- tests/test-data/bridges/moderationBridge.ts
- tests/test-data/bridges/userBridge.ts
- Added Bridge for Deactivating reported user
- Added Bridge for Deleting reported messages
- Added Bridge for resetting reported users' avatar
- Continuing the work on the previous Moderation bridge
https://github.com/RocketChat/Rocket.Chat/pull/28518
If possible, please review it ASAP. Thank you!
> feat: Bridge delete, deactivate moderation features

- package-lock.json
- package.json
> bump: bump vm2 version

- package-lock.json
- package.json
> Bump/bump vm2 3.9.19

- package.json
> 1.39.1-alpha

- src/server/managers/AppListenerManager.ts
This is a small change but actually makes the usage a bit smart
> chore: Type executeListener properly

- src/definition/uikit/UIKitIncomingInteractionTypes.ts
- src/definition/uikit/UIKitInteractionContext.ts
> feat: add `threadId` to interaction context

- src/definition/uikit/UIKitIncomingInteractionTypes.ts
> fix: add missing `threadId` to `IUIKitActionButtonIncomingInteraction`

- src/server/permissions/AppPermissions.ts
- Removed Role permissioms from `defaultPermissions` array.
https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/653#discussion_r1286091372
> chore: Remove roles from default permissions

- deno-runtime/lib/messenger.ts
- deno-runtime/main.ts
- src/server/runtime/AppsEngineDenoRuntime.ts
> Improve runtime API and JSON RPC related functions

- deno-runtime/deno.jsonc
- deno-runtime/deno.lock
- deno-runtime/handlers/slashcommand-handler.ts
- deno-runtime/handlers/tests/slashcommand-handler.test.ts
- deno-runtime/lib/accessors/mod.ts
- deno-runtime/lib/logger.ts
- deno-runtime/lib/require.ts
- deno-runtime/lib/tests/logger.test.ts
- deno-runtime/lib/tests/messenger.test.ts
- deno-runtime/main.ts
- src/server/ProxiedApp.ts
- src/server/managers/AppSlashCommand.ts
- src/server/managers/AppSlashCommandManager.ts
- src/server/runtime/AppsEngineDenoRuntime.ts
- tests/server/managers/AppSlashCommandManager.spec.ts
Refactor slashcommand execution in the engine for the new Runtime API
> Refactor slashcommand execution to new Runtime API

- deno-runtime/handlers/app/construct.ts
- deno-runtime/handlers/app/handleGetStatus.ts
- deno-runtime/handlers/app/handleOnDisable.ts
- deno-runtime/handlers/app/handleOnEnable.ts
- deno-runtime/handlers/app/handleOnInstall.ts
- deno-runtime/handlers/app/handleOnPreSettingUpdate.ts
- deno-runtime/handlers/app/handleOnSettingUpdated.ts
- deno-runtime/handlers/app/handleOnUninstall.ts
- deno-runtime/handlers/app/handleSetStatus.ts
- deno-runtime/handlers/app/handler.ts
- deno-runtime/handlers/app/initialize.ts
- src/server/AppManager.ts
Refactored calls of app lifecycle methods and added their handlers on Deno side
> Add handlers for App methods on Deno and refactor their usages on Node

- deno-runtime/handlers/tests/videoconference-handler.test.ts
- deno-runtime/handlers/videoconference-handler.ts
- deno-runtime/main.ts
- src/server/managers/AppVideoConfProvider.ts
Add handler for video conference
> feat: videoconf handler

- deno-runtime/handlers/app/handler.ts
- deno-runtime/handlers/tests/uikit-handler.test.ts
- deno-runtime/handlers/uikit/handler.ts
- src/server/managers/AppListenerManager.ts
> Add handlers for UIKit methods in Deno and refactor Manager usage

- deno-runtime/handlers/api-handler.ts
- deno-runtime/handlers/tests/api-handler.test.ts
- deno-runtime/main.ts
- src/server/managers/AppApi.ts
- tests/server/managers/AppApiManager.spec.ts
> feat: add api handler

- src/server/AppManager.ts
- src/server/ProxiedApp.ts
> Refactor getAppUserUsername usages

- src/server/ProxiedApp.ts
> Remove `getAccessors` from ProxiedApp

- src/server/runtime/AppsEngineDenoRuntime.ts
> Debugging improvements and some ironing out

- deno-runtime/handlers/app/construct.ts
- deno-runtime/handlers/listener/handler.ts
- deno-runtime/lib/accessors/mod.ts
- src/server/accessors/UploadCreator.ts
> fix: add Buffer conversion for file uploads

- src/server/AppManager.ts
- src/server/compiler/AppCompiler.ts
- src/server/managers/AppRuntimeManager.ts
- src/server/runtime/AppsEngineDenoRuntime.ts
- tests/test-data/utilities.ts
> Add a routine to stop the subprocess in the applicable situations

- deno-runtime/lib/accessors/builders/BlockBuilder.ts
- deno-runtime/lib/accessors/modify/ModifyCreator.ts
- deno-runtime/lib/accessors/modify/ModifyExtender.ts
- deno-runtime/lib/accessors/modify/ModifyUpdater.ts
- deno-runtime/lib/accessors/tests/ModifyCreator.test.ts
- deno-runtime/lib/accessors/tests/ModifyExtender.test.ts
- deno-runtime/lib/accessors/tests/ModifyUpdater.test.ts
- src/server/runtime/AppsEngineDenoRuntime.ts
> fix: bridges

- deno-runtime/lib/accessors/mod.ts
- deno-runtime/lib/accessors/tests/AppAccessors.test.ts
- deno-runtime/main.ts
> fix: accessors proxy message

- deno-runtime/handlers/app/construct.ts
- deno-runtime/handlers/listener/handler.ts
- deno-runtime/lib/accessors/mod.ts
> fix: buffer import

- deno-runtime/handlers/app/handler.ts
- deno-runtime/handlers/listener/handler.ts
- deno-runtime/lib/accessors/mod.ts
- src/server/oauth2/OAuth2Client.ts
> fix: providedApiEndpoints

- deno-runtime/lib/accessors/mod.ts
- src/server/oauth2/OAuth2Client.ts
> fix: get providedApiEndpoints from registered endpoints

- src/server/runtime/AppsEngineDenoRuntime.ts
- Register a listener for response before sending a request from Node
- Fix typos and remove debug
> Small refactors

- deno-runtime/lib/messenger.ts
- deno-runtime/lib/tests/messenger.test.ts
Introduce a queue to ensure messages only get sent when the previous one has been completely sent over the stream (`Deno.stdout`)
> Add Queue to Messenger

- src/server/runtime/AppsEngineDenoRuntime.ts
- Fix bridge success response when result is undefined
- Improve logs on msgpack object handling error
> Fix bridge response when result is undefined

- deno-runtime/handlers/listener/handler.ts
[VM2-13](https://rocketchat.atlassian.net/browse/VM2-13)
[VM2-13]: https://rocketchat.atlassian.net/browse/VM2-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove buffer

- deno-runtime/.vscode/settings.json
- deno-runtime/handlers/tests/listener-handler.test.ts
- deno-runtime/handlers/tests/slashcommand-handler.test.ts
- deno-runtime/lib/ast/mod.ts
- deno-runtime/lib/ast/operations.ts
- deno-runtime/lib/room.ts
- deno-runtime/lib/roomFactory.ts
> fix: wrap `room.usernames` with await

- src/server/runtime/deno/AppsEngineDenoRuntime.ts
> fix: deno wrapper path

- deno-runtime/handlers/tests/api-handler.test.ts
> fix: test api endpoint import

- src/server/managers/AppVideoConfProvider.ts
> Fix video conf provider calls

- deno-runtime/lib/accessors/extenders/HttpExtender.ts
- deno-runtime/lib/accessors/http.ts
- deno-runtime/lib/accessors/mod.ts
- src/server/accessors/Http.ts
> fix: http extend handlers

- deno-runtime/handlers/app/construct.ts
> feat: allow fs module

- src/server/runtime/deno/AppsEngineDenoRuntime.ts
Improve ping strategy. Now we will have only one on going ping call instead of sending pings every 5s regardless of whether the previous ones are still waiting for a response
> Improve ping

- src/definition/livechat/ILivechatRoom.ts
> fix: `OmnichannelSource` type

- src/definition/accessors/ILivechatCreator.ts
> feat: allow custom fields on livechat room creation

- .gitignore
- deno-runtime/handlers/tests/videoconference-handler.test.ts
- deno-runtime/handlers/videoconference-handler.ts
- deno-runtime/lib/accessors/mod.ts
- deno-runtime/lib/accessors/modify/ModifyCreator.ts
- deno-runtime/lib/accessors/modify/ModifyUpdater.ts
- package-lock.json
- package.json
- scripts/postinstall.js
- src/server/AppManager.ts
- src/server/managers/AppVideoConfProvider.ts
- src/server/runtime/deno/AppsEngineDenoRuntime.ts
- tsconfig-lint.json
- fix: optional methods in video conf providers not being handled correctly (#785)
- fix: handler errors no being sent to subprocess (#784)
- fix: errors during updates and uninstallations when runtime or subprocess is invalid (#787)
- feat: improve package installation and deno caching (#786)
> Release 1.43.1

- src/definition/ui/UIActionButtonContext.ts
- src/definition/uikit/IUIKitIncomingInteractionActionButton.ts
- Added a new context for ✨ menu actions
- [Task](https://rocketchat.atlassian.net/browse/SAFE-51)
- [ADR](https://adr.rocket.chat/0101)
> feat: add new UI context

- deno-runtime/lib/accessors/notifier.ts
Fixed an issue with one `import` clause in the Notifier file in deno
> fix: notifier import issue

- src/definition/ui/UIActionButtonContext.ts
- src/definition/uikit/IUIKitIncomingInteractionActionButton.ts
Reverts RocketChat/Rocket.Chat.Apps-engine#794 in favor of #804
> Revert "feat: add new UI context"

- src/definition/ui/IUIActionButtonDescriptor.ts
- Added `categories` for `IUIActionButtonDescriptor`
- Better way to control and render action buttons on the UI
- [RCAI-16](https://rocketchat.atlassian.net/browse/RCAI-16)
[RCAI-16]: https://rocketchat.atlassian.net/browse/RCAI-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: introduce new categories field for UI Action Buttons
